import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/providers";
import Navbar from "@/components/navbar";
import { ViewTransitionProvider } from "@/components/view-transitions";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
  	variable: "--font-geist-mono",
	weight: "100 900",
});

const NewsreaderItalic = localFont({
	src: "./fonts/NewsreaderItalicVF.ttf",
	variable: "--font-newsreader",
	weight: "400",
});



export const metadata: Metadata = {
	title: "Create Next App",
  	description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {

	return (
		<html lang="en" suppressHydrationWarning>
      		<body
        		className={ `${ geistSans.variable } ${ geistMono.variable } ${ NewsreaderItalic.variable } font-sans antialiased` }
      		>
				<Providers>
					
					<ViewTransitionProvider>
						<div className="top-shadow top-0 bg-gradient-to-b from-gray-1 to-transparent" />
						<main className="mx-auto max-w-screen-sm px-6 py-[calc(4vw+6vh)]">
							{ children }
						</main>
						<Navbar />
						<div className="bottom-shadow bottom-0 bg-gradient-to-t from-gray-1 to-transparent" />
                	</ViewTransitionProvider>
					
				</Providers>
      		</body>
    	</html>
  	);
}